name: Ruby

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby_version: [2.4, 2.5, 2.6]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
